services:
  # (contoh) Web API-mu yang sudah ada
  - type: web
    name: magangpulse-api
    runtime: docker
    plan: starter
    region: singapore
    repo: https://github.com/Rendika7/magangpulse-app-monitoring-maganghub-kemnaker
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BASE_URL
        value: https://maganghub.kemnaker.go.id/lowongan
      - key: DATABASE_URL
        sync: false            # supaya diisi via dashboard saat pertama deploy
      - key: DB_PATH
        value: backend/data.sqlite
      - key: USER_AGENT
        value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
      - key: REQUEST_TIMEOUT
        value: "30"
      - key: THROTTLE_SECONDS
        value: "1.0"
      - key: MAX_PAGES
        value: "999999"
      - key: USE_PLAYWRIGHT
        value: "1"
      - key: DETAIL_ENRICH
        value: "1"
      - key: DETAIL_MAX
        value: "999999"
      - key: DETAIL_WORKERS
        value: "6"

  # ➜ Cron Job untuk rescrape tiap 4 jam (UTC)
  - type: cron
    name: scrape-every-4h
    runtime: docker
    plan: starter           # cron job tidak tersedia di plan Free
    region: singapore
    repo: https://github.com/Rendika7/magangpulse-app-monitoring-maganghub-kemnaker
    branch: main
    dockerfilePath: ./Dockerfile
    dockerCommand: "python -m backend.scraper.run_full_scrape"
    schedule: "0 */4 * * *" # setiap 4 jam (timezone: UTC)
    envVars:                # pakai env yang sama dengan web API
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        value: https://maganghub.kemnaker.go.id/lowongan
      - key: USER_AGENT
        value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
      - key: REQUEST_TIMEOUT
        value: "30"
      - key: THROTTLE_SECONDS
        value: "1.0"
      - key: MAX_PAGES
        value: "999999"
      - key: USE_PLAYWRIGHT
        value: "1"
      - key: DETAIL_ENRICH
        value: "1"
      - key: DETAIL_MAX
        value: "999999"
      - key: DETAIL_WORKERS
        value: "6"